# user-authorization-uri: This uri is used to get the tokens.
#token-info-uri : This uri is used to validate the token.
#client-id and client-secret should be in encrypted form not in plain text.
#security:
 # oauth2:
  #  client:
   #   client-id: mobile
    #  client-secret: pin
     # user-authorization-uri: http://localhost:8282/oauth/authorize
      #access-token-uri: http://localhost:8282/oauth/token
   # resource:
    #  token-info-uri: http://localhost:8282/oauth/check_token

#This configuration is used the UI service to see/access the generated token.
#In KSESSION it will set the generated token like below as part of Response Headers
#Set-Cookie: KSESSION=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OD;
server:
  servlet:
    session:
      cookie:
        name: KSESSION
  port: 8081
 
spring:
  application:
    name: edge-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
#zuul:
 # routes:
  #  ui-service:
   #   path: /customers
    #  url: http://localhost:8080
   # profile-service:
    #  path: /profile-service/**
    #  url: http://localhost:8082

zuul:
  routes:
    uiservice:
      path: /ui-api/**
      serviceId: ui-service
    profileservice:
      path: /profile-api/**
      serviceId: profile-service
    auth:
      sensitiveHeaders:
      path: /oauth/**
      serviceId: oauth-service
